tasks:
  - init: |
      sudo apt update && sudo apt install -y python3 python3-pip curl
      pip3 install -r requirements.txt
      curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
      chmod +x cloudflared
